const translations = {
  fr: {
    "career-message": "Débutez votre carrière dans un domaine prometteur dès maintenant !",
    "nav-accueil": "Accueil",
    "nav-gouvernance": "Gouvernance",
    "nav-mot-directeur": "Mot du directeur",
    "nav-historique": "Historique",
    "nav-administration": "Administration",
    "nav-distinction": "Distinction",
    "nav-service": "Service à la communauté",
    "nav-actes": "Actes académiques",
    "nav-formation": "Formation",
    "nav-admission": "Admission",
    "nav-pedagogie": "Pédagogie",
    "nav-licence": "Licence",
    "nav-master": "Master",
    "nav-continu": "Formation continue",
    "nav-doctorat": "Doctorat",
    "nav-recherche": "Recherche",
    "nav-memoire": "Mémoire",
    "nav-travaux": "Travaux des étudiants",
    "nav-formation-continue": "Formation continue",
    "nav-unite": "Unité de recherche",
    "nav-vie": "Vie estudiantine",
    "nav-clubs": "Clubs et associations",
    "nav-sport": "Vie sportive",
    "nav-culture": "Activités culturelles",
    "nav-bourses": "Bourses et aides",
    "nav-contact": "Contact",
    "carousel-msg-1": "Benin Workshop on Artificial Intelligence ( BWAI-21), la deuxième édition aura lieu du 20 au 24 décembre 2021 à l'Université d'Abomey-Calavi, Bénin.",
    "carousel-date-1": "17/02/2022",
    "carousel-link-1": "Lire plus",
    "carousel-msg-2": "Cérémonie de remise de diplôme de Licence et de Master",
    "carousel-date-2": "14/02/2022",
    "carousel-msg-3": "Master 2024-2025",
    "carousel-date-3": "18/06/2024",
    "btn-discover": "Découvrez nos formations",
    "card-title-1": "Innovation",
    "card-text-1": "Les étudiants de l'IFRI sont formés avec le goût pour l'innovation et l'entreprenariat afin de développer des solutions pour résoudre des problèmes spécifiques de leur milieu de vie, et du monde en général.",
    "card-title-2": "Recherche",
    "card-text-2": "L'institut dispose d'un laboratoire de recherche en science informatique et application qui permet aux doctorants et aux enseignants de mener des travaux de recherches et d'innovations.",
    "card-title-3": "Certification",
    "card-text-3": "Le programme de formation dans l'institut contient des cours de certifications dans divers domaines. Ainsi nos étudiants en L3 suivent les cours de certifications CCNA, CND, CEH, Mikrotik, Oracle.",
    "director-title": "Mot du directeur",
    "director-text": "La vocation de l'Institut de Formation et de Recherche en Informatique (IFRI) de l'Université d'Abomey-Calavi est de former des apprenants capables de devenir des acteurs de solutions informatiques aux différents problèmes de société en s'appuyant sur les récents développements des Technologies de l'Information et de la Communication. Les performances des étudiants de l'IFRI font parler de l'Institut au plan national qu'international...",
    "stats-title": "NOS DERNIÈRES STATISTIQUES",
    "stats-awards": "Distinctions",
    "stats-licence": "Filières en Licence",
    "stats-master": "Filières en Master",
    "stats-doctorate": "Filières en Doctorat",
    "stats-trainings": "Formations",
    "stats-students": "Étudiants",
    "stats-admitted": "Admis",
    "stats-admission": "Admission",
    "stats-read-more": "Lire toute l'information →",
    "partners-title": "NOS PARTENAIRES",
    "partners-logo-header": "Logo",
    "partners-name-header": "Nom partenaire",
    "partners-location-header": "Situation géographique",
    "partners-domain-header": "Domaine d'activité",
    "partner-1-name": "Université Catholique de Louvain",
    "partner-1-location": "Belgique, avec des campus à Louvain-la-Neuve, Bruxelles Woluwe, Mons, Tournai, Charleroi et Bruxelles Saint-Gilles",
    "partner-1-domain": "Enseignement supérieur et recherche",
    "partner-2-name": "ENEAM",
    "partner-2-location": "UAC, Abomey-Calavi, Bénin",
    "partner-2-domain": "Formation en économie appliquée, gestion et management",
    "partner-3-name": "EPAC",
    "partner-3-location": "UAC, Abomey-Calavi, Bénin",
    "partner-3-domain": "Formation en ingénierie et technologies appliquées",
    "partner-4-name": "IMSP",
    "partner-4-location": "Dangbo, Bénin",
    "partner-4-domain": "Recherche et formation en mathématiques et sciences physiques",
    "partner-5-name": "Danktic Consulting",
    "partner-5-location": "Cotonou, Bénin",
    "partner-5-domain": "Conseil en technologies de l'information et communication",
    "partner-6-name": "OPENSI",
    "partner-6-location": "Cotonou, Bénin",
    "partner-6-domain": "Solutions informatiques et services numériques",
    "partners-see-all": "Tout voir",
    "testimonials-title": "Nos étudiants témoignent",
    "testimonial-1-text": "“Je me suis inscrite en licence professionnelle de Sécurité Informatique à l’IFRI car ici on a accès à une formation de qualité et une bonne ambiance de travail. Je pense qu’en suivant la formation offerte dans cet institut, je pourrai réaliser beaucoup d’exploits.”",
    "testimonial-1-name": "CODJIA DÉBORA FIFAMÈ",
    "testimonial-1-role": "Étudiante en Sécurité Informatique",
    "testimonial-2-text": "“IFRI est la meilleure école informatique du Bénin, par excellence. Elle nous offre une formation hyper rigoureuse, avec beaucoup de pression mais on apprend beaucoup de choses.”",
    "testimonial-2-name": "OROU BADE Aïchatou",
    "testimonial-2-role": "Étudiante en fin de formation en internet et multimédia",
    "testimonial-3-text": "“M’inscrire en licence professionnelle de Sécurité informatique à l’IFRI a été le bon choix pour moi pour plusieurs raisons. La principale est que j’ai suivi un programme académique rigoureux qui me mettait au défi chaque jour afin que je me perfectionne.”",
    "testimonial-3-name": "MICHOAGAN Hospice",
    "testimonial-3-role": "Technicien en Sécurité Informatique",
    "training-catalog-title": "Catalogue des formations",
    "footer-ifri-title": "IFRI",
    "footer-message-director": "Mot du directeur",
    "footer-history": "Historique",
    "footer-administration": "Administration",
    "footer-pedagogy": "Pédagogie",
    "footer-distinction": "Distinction",
    "footer-contact": "Contact",
    "footer-community-service": "Service à la communauté",
    "footer-more-title": "En plus",
    "footer-admission": "Admission",
    "footer-training": "Formation",
    "footer-laboratory": "Laboratoire",
    "footer-cooperation": "Coopération",
    "footer-thesis": "Mémoire",
    "footer-student-works": "Travaux étudiants",
    "footer-student-life-title": "Vie estudiantine",
    "footer-internship": "Stage et alternance",
    "footer-wicsi": "WICSI",
    "footer-cultural-activities": "Activités culturelles",
    "footer-alumni": "Alumni",
    "footer-gallery": "Galerie",
    "footer-follow-us-title": "Suivez-nous",
    "footer-facebook": "Facebook",
    "footer-instagram": "Instagram",
    "footer-youtube": "Youtube",
    "footer-linkedin": "LinkedIn",
    "footer-copyright": "Copyright IFRI-UAC 2025"
  },
  en: {
    "career-message": "Start your career in a promising field now!",
    "nav-accueil": "Home",
    "nav-gouvernance": "Governance",
    "nav-mot-directeur": "Director's Message",
    "nav-historique": "History",
    "nav-administration": "Administration",
    "nav-distinction": "Award",
    "nav-service": "Community Service",
    "nav-actes": "Academic Records",
    "nav-formation": "Programs",
    "nav-admission": "Admission",
    "nav-pedagogie": "Teaching",
    "nav-licence": "Bachelor",
    "nav-master": "Master",
    "nav-continu": "Continuing Education",
    "nav-doctorat": "PhD",
    "nav-recherche": "Research",
    "nav-memoire": "Thesis",
    "nav-travaux": "Student Works",
    "nav-formation-continue": "Continuing Education",
    "nav-unite": "Research Unit",
    "nav-vie": "Student Life",
    "nav-clubs": "Clubs & Associations",
    "nav-sport": "Sports Life",
    "nav-culture": "Cultural Activities",
    "nav-bourses": "Scholarships & Aid",
    "nav-contact": "Contact",
    "carousel-msg-1": "Benin Workshop on Artificial Intelligence (BWAI-21), the second edition will take place from December 20 to 24, 2021 at the University of Abomey-Calavi, Benin.",
    "carousel-date-1": "02/17/2022",
    "carousel-link-1": "Read more",
    "carousel-msg-2": "Bachelor and Master Degree Award Ceremony",
    "carousel-date-2": "02/14/2022",
    "carousel-msg-3": "Master 2024-2025",
    "carousel-date-3": "06/18/2024",
    "btn-discover": "Discover our programs",
    "card-title-1": "Innovation",
    "card-text-1": "IFRI students are trained with a taste for innovation and entrepreneurship to develop solutions that solve specific problems in their environment and in the world at large.",
    "card-title-2": "Research",
    "card-text-2": "The institute has a research laboratory in computer science and applications that enables PhD students and teachers to carry out research and innovation work.",
    "card-title-3": "Certification",
    "card-text-3": "The institute’s training program includes certification courses in various fields. Our third-year students follow certification courses in CCNA, CND, CEH, Mikrotik, Oracle.",
    "director-title": "Director's Message",
    "director-text": "The mission of the Institute for Training and Research in Computer Science (IFRI) at the University of Abomey-Calavi is to train learners capable of becoming key players in IT solutions to societal problems, based on recent developments in Information and Communication Technologies. The performance of IFRI students has earned the Institute recognition both nationally and internationally...",
    "stats-title": "OUR LATEST STATISTICS",
    "stats-awards": "Awards",
    "stats-licence": "Bachelor Programs",
    "stats-master": "Master Programs",
    "stats-doctorate": "Doctoral Programs",
    "stats-trainings": "Trainings",
    "stats-students": "Students",
    "stats-admitted": "Admitted",
    "stats-admission": "Admission",
    "stats-read-more": "Read all information →",
    "partners-title": "OUR PARTNERS",
    "partners-logo-header": "Logo",
    "partners-name-header": "Partner name",
    "partners-location-header": "Location",
    "partners-domain-header": "Field of Activity",
    "partner-1-name": "Catholic University of Louvain",
    "partner-1-location": "Belgium, with campuses in Louvain-la-Neuve, Brussels Woluwe, Mons, Tournai, Charleroi and Brussels Saint-Gilles",
    "partner-1-domain": "Higher education and research",
    "partner-2-name": "ENEAM",
    "partner-2-location": "UAC, Abomey-Calavi, Benin",
    "partner-2-domain": "Training in applied economics, management and administration",
    "partner-3-name": "EPAC",
    "partner-3-location": "UAC, Abomey-Calavi, Benin",
    "partner-3-domain": "Engineering and applied technologies training",
    "partner-4-name": "IMSP",
    "partner-4-location": "Dangbo, Benin",
    "partner-4-domain": "Research and training in mathematics and physical sciences",
    "partner-5-name": "Danktic Consulting",
    "partner-5-location": "Cotonou, Benin",
    "partner-5-domain": "IT and communication technology consulting",
    "partner-6-name": "OPENSI",
    "partner-6-location": "Cotonou, Benin",
    "partner-6-domain": "IT solutions and digital services",
    "partners-see-all": "See all",
    "testimonials-title": "Our Students Testify",
    "testimonial-1-text": "“I enrolled in the professional Bachelor's degree in Cybersecurity at IFRI because it offers quality training and a great working atmosphere. I believe that with the training offered by this institute, I will achieve many great things.”",
    "testimonial-1-name": "CODJIA DÉBORA FIFAMÈ",
    "testimonial-1-role": "Cybersecurity Student",
    "testimonial-2-text": "“IFRI is the best IT school in Benin, without a doubt. It offers us extremely rigorous training, with a lot of pressure, but we learn a lot.”",
    "testimonial-2-name": "OROU BADE Aïchatou",
    "testimonial-2-role": "Graduating student in Internet and Multimedia",
    "testimonial-3-text": "“Enrolling in the professional Bachelor's in Cybersecurity at IFRI was the right choice for many reasons. The main one is that I followed a rigorous academic program that challenged me every day to improve myself.”",
    "testimonial-3-name": "MICHOAGAN Hospice",
    "testimonial-3-role": "Cybersecurity Technician",
    "training-catalog-title": "Training Catalog",
    "footer-ifri-title": "IFRI",
    "footer-message-director": "Director's Message",
    "footer-history": "History",
    "footer-administration": "Administration",
    "footer-pedagogy": "Pedagogy",
    "footer-distinction": "Distinction",
    "footer-contact": "Contact",
    "footer-community-service": "Community Service",
    "footer-more-title": "More",
    "footer-admission": "Admission",
    "footer-training": "Training",
    "footer-laboratory": "Laboratory",
    "footer-cooperation": "Cooperation",
    "footer-thesis": "Thesis",
    "footer-student-works": "Student Works",
    "footer-student-life-title": "Student Life",
    "footer-internship": "Internships and Apprenticeships",
    "footer-wicsi": "WICSI",
    "footer-cultural-activities": "Cultural Activities",
    "footer-alumni": "Alumni",
    "footer-gallery": "Gallery",
    "footer-follow-us-title": "Follow Us",
    "footer-facebook": "Facebook",
    "footer-instagram": "Instagram",
    "footer-youtube": "YouTube",
    "footer-linkedin": "LinkedIn",
    "footer-copyright": "Copyright IFRI-UAC 2025"
  }
};

function setLanguage(lang) {
  const langStrings = translations[lang];
  if (!langStrings) return;

  for (const id in langStrings) {
    const element = document.getElementById(id);
    if (element) {
      element.textContent = langStrings[id];
    }
  }

  document.documentElement.lang = lang;
  localStorage.setItem("lang", lang);
}

window.addEventListener("DOMContentLoaded", () => {
  const savedLang = localStorage.getItem("lang");
  const langToUse = translations[savedLang] ? savedLang : "fr";
  setLanguage(langToUse);
});
